version: '3.3'
services:
  mongodb:
    image: mongo:4.0.4
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - data:/data/db

volumes:
  data:
    driver: local